# Book settings
title: Introduction to Akkadian  # The title of the book. Will be placed in the left navbar.
author: Shai Gordin and Luis Sáenz  # The author of the book
execute:
  execute_notebooks: force
  
# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib