# Book settings
title: Introduction to Akkadian  # The title of the book. Will be placed in the left navbar.
author: Shai Gordin and Luis Sáenz  # The author of the book
execute:
  execute_notebooks: force

# References-Bibliography
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year