# Book settings
title: "eAkkadian"  # The title of the book. Will be placed in the left navbar.
author: Shai Gordin, Luis Sáenz and Morris Alper  # The author of the book
execute:
  execute_notebooks: force

# References-Bibliography
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year

# Information about where the book exists on the web
repository:
  url: https://github.com/DigitalPasts/eAkkadian/  # Online location of your book
  branch : main  # Which branch of the repository should be used when creating links (optional)
html:
  use_repository_button: true
  use_issues_button: true

